### ISSUE TITLE
Feedback sobre Cadastrar histórias no gitHub

### ISSUE THREAD

**Issue by lsca** [IF977/SchoolClue#7]
Fala galera, tudo certinho??

Fiquei de corrigir "Cadastrar histórias no gitHub" na it2 de vocês, mas não entendi como estão organizar as issues de vocês. Nada foi cadastrado para a it2?

**Comment by Arthur-Justino** [comment]
Opa, tudo certo!
Foi sim, a história da it2 está com o nome "formulário atividades complementares"

**Comment by lsca** [comment]
Só foi feita 1 hu?

**Comment by Arthur-Justino** [comment]
para a it2 sim

**Comment by lsca** [comment]
Beleza, penalização de 3 pontos por só ter feita 1 issue com um grupo de 3 pessoas. Não foi utilizada ISSUE e nem Milestone penalizando 1 ponto por cada.
10-3-1-1 = 5.

![image](https://user-images.githubusercontent.com/13456954/26899841-d5d3c39e-4ba6-11e7-984d-69592cfe0ab0.png)
